C_RE_UNIT = r'UNIT\s*([\.\w]+)\s*;'
C_RE_INTERFACE = r'INTERFACE\s+'
C_RE_IMPLEMENTATION = r'IMPLEMENTATION\s+'
C_RE_END_FINAL = r'END\s*\.'
C_RE_USES = r'USES[ ]*((?:[^,;]+[ ]*,[ ]*)*[^,;]+)[ ]*;'
C_RE_TYPES = r'TYPE\s'
C_RE_DECL_TYPE = r'([^= ]+)[ ]*=[ ]*([^;]+)[ ]*;'
C_RE_DECL_TYPE_SETOF = r'([^= ]+)[ ]*=[ ]*SET[ ]*OF[ ]*([^;]+)[ ]*;'
C_RE_CLASS = r'(\w+)[ ]*=[ ]*CLASS[ ]*(?:\(([^\)]*)\))?.*?END\s*;'
C_RE_CLASS_DEB = r'(\w+)[ ]*=[ ]*(CLASS|RECORD|INTERFACE)[ ]*(?:\(([^\)]*)\))?'
C_RE_END = r'END\s*;'
C_RE_RECORD = r'(\w+)[ ]*=[ ]*RECORD[ ]*.*END\s*;'
C_RE_TYPE_PROC_FUNC = r'(\w+)[ ]*=[ ]*(?:REFERENCE)?[ ]*(?:TO)?[ ]*((?:PROCEDURE|FUNCTION)[ ]*\(.*?\)[ ]*(?:OF)?[ ]*(?:OBJECT)?[ ]*);'
C_RE_PARAM = r'\s*(CONST|VAR|OUT)?\s+([^:]+)\s*:\s*([\w<> ]+)\s*;?'
C_RE_FUNCTION_DECL = r'FUNCTION[ ]+([^ \(]+)[ ]*\(([^\)]*)\)[ ]*:[ ]*([^;]*);(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_FUNCTION_IMPL = r'FUNCTION[ ]+(%s)[ ]*\(([^\(\)]*)\)[ ]*:[ ]*([^;]*);(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_FUNCTION_DECL_S = r'FUNCTION[ ]+([^ \(]+)[ ]*[ ]*:[ ]*([^;]*);(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_FUNCTION_IMPL_S = r'FUNCTION[ ]+(%s)[ ]*[ ]*:[ ]*([^;]*);(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_PROCEDURE_DECL = r'(?:PROCEDURE|CONSTRUCTOR|DESTRUCTOR)[ ]+([^ \(]+)[ ]*\(([^\)]*)\)[ ]*;(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_PROCEDURE_IMPL = r'(?:PROCEDURE|CONSTRUCTOR|DESTRUCTOR)[ ]+(%s)[ ]*\(([^\)]*)\)[ ]*;(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_PROCEDURE_DECL_S = r'(?:PROCEDURE|CONSTRUCTOR|DESTRUCTOR)[ ]+([^ \(]+)[ ]*;(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_PROCEDURE_IMPL_S = r'(?:PROCEDURE|CONSTRUCTOR|DESTRUCTOR)[ ]+(%s)[ ]*;(?:[ ]*(OVERLOAD|OVERRIDE|VIRTUAL|ABSTRACT)[ ]*;)?'
C_RE_PROCEDURE_FUNCTION_DEB = r'(PROCEDURE|CONSTRUCTOR|FUNCTION|DESTRUCTOR)[ ]+'
C_RE_SECTION_CLASS = r'(PUBLIC|PRIVATE|PROTECTED|PUBLISHED)\s+'
C_RE_VAR = r'((?:\w+\,?\s*)+):\s*([^;]+?)\s*;'
C_RE_PROPERTY = r'PROPERTY\s+(\w+)\s*:\s*(\w+)\s*(?:(READ)\s*(\w+))?\s*(?:(WRITE)\s*(\w+))?\s*(?:(IMPLEMENTS)\s*(\w+))?;'
C_RE_SECTION_CONST = r'CONST\s+'
C_RE_DEF_CONST = r'(\w+)\s*(?:([^=;]+)\s*)?=\s*([^;]+);'
C_RE_SECTION_RESOURCE = r'RESOURCESTRING\s+'
C_RE_DEF_RESOURCE = r'(\w+)\s*=\s*([^;]+);'
C_RE_SECTION = r'(IMPLEMENTATION|TYPE|CONST|RESOURCESTRING|PROCEDURE|FUNCTION)\s+'
C_RE_GUID = r'\[\s*\'[^\']*\'\s*\]'
